// Code generated by go-swagger; DO NOT EDIT.

package kv

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewKeyDeleteParams creates a new KeyDeleteParams object
// no default values defined in spec.
func NewKeyDeleteParams() KeyDeleteParams {

	return KeyDeleteParams{}
}

// KeyDeleteParams contains all the bound params for the key delete operation
// typically these are obtained from a http.Request
//
// swagger:parameters KeyDelete
type KeyDeleteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The key for a given entry
	  Required: true
	  Min Length: 1
	  In: path
	*/
	Key string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewKeyDeleteParams() beforehand.
func (o *KeyDeleteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rKey, rhkKey, _ := route.Params.GetOK("key")
	if err := o.bindKey(rKey, rhkKey, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindKey binds and validates parameter Key from path.
func (o *KeyDeleteParams) bindKey(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Key = raw

	if err := o.validateKey(formats); err != nil {
		return err
	}

	return nil
}

// validateKey carries on validations for parameter Key
func (o *KeyDeleteParams) validateKey(formats strfmt.Registry) error {

	if err := validate.MinLength("key", "path", o.Key, 1); err != nil {
		return err
	}

	return nil
}
