// Code generated by go-swagger; DO NOT EDIT.

package kv

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// KeyDeleteHandlerFunc turns a function with the right signature into a key delete handler
type KeyDeleteHandlerFunc func(KeyDeleteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn KeyDeleteHandlerFunc) Handle(params KeyDeleteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// KeyDeleteHandler interface for that can handle valid key delete params
type KeyDeleteHandler interface {
	Handle(KeyDeleteParams, interface{}) middleware.Responder
}

// NewKeyDelete creates a new http.Handler for the key delete operation
func NewKeyDelete(ctx *middleware.Context, handler KeyDeleteHandler) *KeyDelete {
	return &KeyDelete{Context: ctx, Handler: handler}
}

/*KeyDelete swagger:route DELETE /kv/{key} kv keyDelete

Delete an existing key

*/
type KeyDelete struct {
	Context *middleware.Context
	Handler KeyDeleteHandler
}

func (o *KeyDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewKeyDeleteParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
