// Code generated by go-swagger; DO NOT EDIT.

package kv

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ValueUpdateHandlerFunc turns a function with the right signature into a value update handler
type ValueUpdateHandlerFunc func(ValueUpdateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ValueUpdateHandlerFunc) Handle(params ValueUpdateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ValueUpdateHandler interface for that can handle valid value update params
type ValueUpdateHandler interface {
	Handle(ValueUpdateParams, interface{}) middleware.Responder
}

// NewValueUpdate creates a new http.Handler for the value update operation
func NewValueUpdate(ctx *middleware.Context, handler ValueUpdateHandler) *ValueUpdate {
	return &ValueUpdate{Context: ctx, Handler: handler}
}

/*ValueUpdate swagger:route PUT /v1alpha/kv kv valueUpdate

Update value

*/
type ValueUpdate struct {
	Context *middleware.Context
	Handler ValueUpdateHandler
}

func (o *ValueUpdate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewValueUpdateParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
