---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: next-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
    storageClassName: glusterfs-storage