---
kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: apikey
  type: Opaque
  data:
    key: YWJjZGUK
- apiVersion: v1
  kind: Secret
  apiVersion: v1
  metadata:
    name: webhooksecret
  data:
    WebHookSecretKey: x4UbcmA1dm4cQGFz