// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Next
Next is a simple single node store for retrieving key/value information


    Schemes:
      http
    Host: localhost
    BasePath: /api
    Version: 0.0.1
    License: Apache 2.0 https://github.com/stevexnicholls/next/blob/master/LICENSE
    Contact: Steve Nicholls<stevexnicholls@gmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json
    - application/octet-stream

swagger:meta
*/
package restapi
