// Code generated by mockery v1.0.0. DO NOT EDIT.

package restapi

import backup "github.com/stevexnicholls/next/restapi/operations/backup"
import context "context"
import middleware "github.com/go-openapi/runtime/middleware"
import mock "github.com/stretchr/testify/mock"

// MockBackupAPI is an autogenerated mock type for the BackupAPI type
type MockBackupAPI struct {
	mock.Mock
}

// BackupGet provides a mock function with given fields: ctx, params
func (_m *MockBackupAPI) BackupGet(ctx context.Context, params backup.BackupGetParams) middleware.Responder {
	ret := _m.Called(ctx, params)

	var r0 middleware.Responder
	if rf, ok := ret.Get(0).(func(context.Context, backup.BackupGetParams) middleware.Responder); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Responder)
		}
	}

	return r0
}
