// Code generated by go-swagger; DO NOT EDIT.

package kv

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewKeyListParams creates a new KeyListParams object
// with the default values initialized.
func NewKeyListParams() *KeyListParams {

	return &KeyListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewKeyListParamsWithTimeout creates a new KeyListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewKeyListParamsWithTimeout(timeout time.Duration) *KeyListParams {

	return &KeyListParams{

		timeout: timeout,
	}
}

// NewKeyListParamsWithContext creates a new KeyListParams object
// with the default values initialized, and the ability to set a context for a request
func NewKeyListParamsWithContext(ctx context.Context) *KeyListParams {

	return &KeyListParams{

		Context: ctx,
	}
}

// NewKeyListParamsWithHTTPClient creates a new KeyListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewKeyListParamsWithHTTPClient(client *http.Client) *KeyListParams {

	return &KeyListParams{
		HTTPClient: client,
	}
}

/*KeyListParams contains all the parameters to send to the API endpoint
for the key list operation typically these are written to a http.Request
*/
type KeyListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the key list params
func (o *KeyListParams) WithTimeout(timeout time.Duration) *KeyListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the key list params
func (o *KeyListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the key list params
func (o *KeyListParams) WithContext(ctx context.Context) *KeyListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the key list params
func (o *KeyListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the key list params
func (o *KeyListParams) WithHTTPClient(client *http.Client) *KeyListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the key list params
func (o *KeyListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *KeyListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
