// Code generated by go-swagger; DO NOT EDIT.

package kv

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewKeyDeleteParams creates a new KeyDeleteParams object
// with the default values initialized.
func NewKeyDeleteParams() *KeyDeleteParams {
	var ()
	return &KeyDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewKeyDeleteParamsWithTimeout creates a new KeyDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewKeyDeleteParamsWithTimeout(timeout time.Duration) *KeyDeleteParams {
	var ()
	return &KeyDeleteParams{

		timeout: timeout,
	}
}

// NewKeyDeleteParamsWithContext creates a new KeyDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewKeyDeleteParamsWithContext(ctx context.Context) *KeyDeleteParams {
	var ()
	return &KeyDeleteParams{

		Context: ctx,
	}
}

// NewKeyDeleteParamsWithHTTPClient creates a new KeyDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewKeyDeleteParamsWithHTTPClient(client *http.Client) *KeyDeleteParams {
	var ()
	return &KeyDeleteParams{
		HTTPClient: client,
	}
}

/*KeyDeleteParams contains all the parameters to send to the API endpoint
for the key delete operation typically these are written to a http.Request
*/
type KeyDeleteParams struct {

	/*Key
	  The key for a given entry

	*/
	Key string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the key delete params
func (o *KeyDeleteParams) WithTimeout(timeout time.Duration) *KeyDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the key delete params
func (o *KeyDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the key delete params
func (o *KeyDeleteParams) WithContext(ctx context.Context) *KeyDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the key delete params
func (o *KeyDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the key delete params
func (o *KeyDeleteParams) WithHTTPClient(client *http.Client) *KeyDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the key delete params
func (o *KeyDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKey adds the key to the key delete params
func (o *KeyDeleteParams) WithKey(key string) *KeyDeleteParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the key delete params
func (o *KeyDeleteParams) SetKey(key string) {
	o.Key = key
}

// WriteToRequest writes these params to a swagger request
func (o *KeyDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
