// Code generated by go-swagger; DO NOT EDIT.

package kv

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewValueGetParams creates a new ValueGetParams object
// with the default values initialized.
func NewValueGetParams() *ValueGetParams {
	var ()
	return &ValueGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewValueGetParamsWithTimeout creates a new ValueGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewValueGetParamsWithTimeout(timeout time.Duration) *ValueGetParams {
	var ()
	return &ValueGetParams{

		timeout: timeout,
	}
}

// NewValueGetParamsWithContext creates a new ValueGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewValueGetParamsWithContext(ctx context.Context) *ValueGetParams {
	var ()
	return &ValueGetParams{

		Context: ctx,
	}
}

// NewValueGetParamsWithHTTPClient creates a new ValueGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewValueGetParamsWithHTTPClient(client *http.Client) *ValueGetParams {
	var ()
	return &ValueGetParams{
		HTTPClient: client,
	}
}

/*ValueGetParams contains all the parameters to send to the API endpoint
for the value get operation typically these are written to a http.Request
*/
type ValueGetParams struct {

	/*Key
	  The key for a given entry

	*/
	Key string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the value get params
func (o *ValueGetParams) WithTimeout(timeout time.Duration) *ValueGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the value get params
func (o *ValueGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the value get params
func (o *ValueGetParams) WithContext(ctx context.Context) *ValueGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the value get params
func (o *ValueGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the value get params
func (o *ValueGetParams) WithHTTPClient(client *http.Client) *ValueGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the value get params
func (o *ValueGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKey adds the key to the value get params
func (o *ValueGetParams) WithKey(key string) *ValueGetParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the value get params
func (o *ValueGetParams) SetKey(key string) {
	o.Key = key
}

// WriteToRequest writes these params to a swagger request
func (o *ValueGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
