// Code generated by go-swagger; DO NOT EDIT.

package kv

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/stevexnicholls/next/models"
)

// NewValueUpdateParams creates a new ValueUpdateParams object
// with the default values initialized.
func NewValueUpdateParams() *ValueUpdateParams {
	var ()
	return &ValueUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewValueUpdateParamsWithTimeout creates a new ValueUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewValueUpdateParamsWithTimeout(timeout time.Duration) *ValueUpdateParams {
	var ()
	return &ValueUpdateParams{

		timeout: timeout,
	}
}

// NewValueUpdateParamsWithContext creates a new ValueUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewValueUpdateParamsWithContext(ctx context.Context) *ValueUpdateParams {
	var ()
	return &ValueUpdateParams{

		Context: ctx,
	}
}

// NewValueUpdateParamsWithHTTPClient creates a new ValueUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewValueUpdateParamsWithHTTPClient(client *http.Client) *ValueUpdateParams {
	var ()
	return &ValueUpdateParams{
		HTTPClient: client,
	}
}

/*ValueUpdateParams contains all the parameters to send to the API endpoint
for the value update operation typically these are written to a http.Request
*/
type ValueUpdateParams struct {

	/*Keyvalue*/
	Keyvalue *models.KeyValue

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the value update params
func (o *ValueUpdateParams) WithTimeout(timeout time.Duration) *ValueUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the value update params
func (o *ValueUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the value update params
func (o *ValueUpdateParams) WithContext(ctx context.Context) *ValueUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the value update params
func (o *ValueUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the value update params
func (o *ValueUpdateParams) WithHTTPClient(client *http.Client) *ValueUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the value update params
func (o *ValueUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKeyvalue adds the keyvalue to the value update params
func (o *ValueUpdateParams) WithKeyvalue(keyvalue *models.KeyValue) *ValueUpdateParams {
	o.SetKeyvalue(keyvalue)
	return o
}

// SetKeyvalue adds the keyvalue to the value update params
func (o *ValueUpdateParams) SetKeyvalue(keyvalue *models.KeyValue) {
	o.Keyvalue = keyvalue
}

// WriteToRequest writes these params to a swagger request
func (o *ValueUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Keyvalue != nil {
		if err := r.SetBodyParam(o.Keyvalue); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
