// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/stevexnicholls/next/models"
)

// BackupGetOKCode is the HTTP code returned for type BackupGetOK
const BackupGetOKCode int = 200

/*BackupGetOK Yay a backup

swagger:response backupGetOK
*/
type BackupGetOK struct {
}

// NewBackupGetOK creates BackupGetOK with default headers values
func NewBackupGetOK() *BackupGetOK {

	return &BackupGetOK{}
}

// WriteResponse to the client
func (o *BackupGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// BackupGetNotFoundCode is the HTTP code returned for type BackupGetNotFound
const BackupGetNotFoundCode int = 404

/*BackupGetNotFound The entry was not found

swagger:response backupGetNotFound
*/
type BackupGetNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBackupGetNotFound creates BackupGetNotFound with default headers values
func NewBackupGetNotFound() *BackupGetNotFound {

	return &BackupGetNotFound{}
}

// WithPayload adds the payload to the backup get not found response
func (o *BackupGetNotFound) WithPayload(payload *models.Error) *BackupGetNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the backup get not found response
func (o *BackupGetNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BackupGetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*BackupGetDefault Error

swagger:response backupGetDefault
*/
type BackupGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBackupGetDefault creates BackupGetDefault with default headers values
func NewBackupGetDefault(code int) *BackupGetDefault {
	if code <= 0 {
		code = 500
	}

	return &BackupGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the backup get default response
func (o *BackupGetDefault) WithStatusCode(code int) *BackupGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the backup get default response
func (o *BackupGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the backup get default response
func (o *BackupGetDefault) WithPayload(payload *models.Error) *BackupGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the backup get default response
func (o *BackupGetDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BackupGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
