// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewHealthGetParams creates a new HealthGetParams object
// with the default values initialized.
func NewHealthGetParams() *HealthGetParams {

	return &HealthGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHealthGetParamsWithTimeout creates a new HealthGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHealthGetParamsWithTimeout(timeout time.Duration) *HealthGetParams {

	return &HealthGetParams{

		timeout: timeout,
	}
}

// NewHealthGetParamsWithContext creates a new HealthGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewHealthGetParamsWithContext(ctx context.Context) *HealthGetParams {

	return &HealthGetParams{

		Context: ctx,
	}
}

// NewHealthGetParamsWithHTTPClient creates a new HealthGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewHealthGetParamsWithHTTPClient(client *http.Client) *HealthGetParams {

	return &HealthGetParams{
		HTTPClient: client,
	}
}

/*HealthGetParams contains all the parameters to send to the API endpoint
for the health get operation typically these are written to a http.Request
*/
type HealthGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the health get params
func (o *HealthGetParams) WithTimeout(timeout time.Duration) *HealthGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the health get params
func (o *HealthGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the health get params
func (o *HealthGetParams) WithContext(ctx context.Context) *HealthGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the health get params
func (o *HealthGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the health get params
func (o *HealthGetParams) WithHTTPClient(client *http.Client) *HealthGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the health get params
func (o *HealthGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *HealthGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
