// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Backup backup
// swagger:model Backup
type Backup strfmt.Base64

// UnmarshalJSON sets a Backup value from JSON input
func (m *Backup) UnmarshalJSON(b []byte) error {
	return ((*strfmt.Base64)(m)).UnmarshalJSON(b)
}

// MarshalJSON retrieves a Backup value as JSON output
func (m Backup) MarshalJSON() ([]byte, error) {
	return (strfmt.Base64(m)).MarshalJSON()
}

// Validate validates this backup
func (m Backup) Validate(formats strfmt.Registry) error {
	var res []error

	// Format "byte" (base64 string) is already validated when unmarshalled

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Backup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Backup) UnmarshalBinary(b []byte) error {
	var res Backup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
